### ISSUE TITLE
[Bug] 无法使用熔炉

### ISSUE THREAD

**Issue by HhiPyrene** [Nyan-Work/plusls-carpet-addition#1]
### Minecraft Version

1.19.3

### Plusls Carpet Addition Version

0.3.144+85a443e

### Carpet Version

1.4.96+v230201

### Fabric API Version

qfapi-5.0.0-beta.6_qsl-4.0.0-beta.11_fapi-0.74.0

### Description

添加此Mod后无法使用熔炉（重新进入世界后会开始工作），无论有没有开启任何Carpet功能.

### To Reproduce

进入世界并使用熔炉、高炉或烟熏炉烧制物品。

### Log

[latest.log](https://github.com/Nyan-Work/plusls-carpet-addition/files/10830474/latest.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by HhiPyrene** [comment]
顺带一提，新版本的PCA完全没法用（悲）

**Comment by Hendrix-Shen** [comment]
熔炉无法使用是因为与锂模组冲突，从 https://github.com/CaffeineMC/lithium-fabric/actions 下载开发版即可解决。新版PCA的规则管理使用独立命令 `/pca`。

**Comment by HhiPyrene** [comment]
> 熔炉无法使用是因为与锂模组冲突，从 https://github.com/CaffeineMC/lithium-fabric/actions 下载开发版即可解决。新版PCA的规则管理使用独立命令 `/pca`。

感谢
