### ISSUE TITLE
[Bug] playerSit 无法 100% 触发

### ISSUE THREAD

**Issue by cat0x1f** [Nyan-Work/plusls-carpet-addition#13]
### Minecraft Version

1.20.1

### Plusls Carpet Addition Version

0.3.169+6510223

### Carpet Version

1.4.112+v230608

### Fabric API Version

0.85

### Description

连按三下 shift，坐下后立刻又自动站起来，要尝试多次才能坐下。

### To Reproduce

连按三下 shift。

### Expected behavior

正常触发 playerSit 功能。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请尝试此版本：[0.3.173+ce1635c](https://github.com/Nyan-Work/plusls-carpet-addition/releases/tag/nyan-work%2Fdev.27)

**Comment by cat0x1f** [comment]
修复好了。谢谢。

**Comment by cat0x1f** [comment]
更新后好像又有问题：Shift + 右键实体 会坐下。旧版本不会这样。

**Comment by Hendrix-Shen** [comment]
[0.3.176+56ccc7d](https://github.com/Nyan-Work/plusls-carpet-addition/releases/tag/nyan-work%2Fdev.28)

**Comment by cat0x1f** [comment]
OK.
