### ISSUE TITLE
1.20.1加载失败

### ISSUE THREAD

**Issue by sillya1a2** [Nyan-Work/plusls-carpet-addition#14]
### Minecraft Version

1.20.1

### Plusls Carpet Addition Version

0.3.169+6510223-beta

### Carpet Version

1.4.112+v230608

### Fabric API Version

-0.85.0+1.20.1

### Description

游戏正常启动，已加载carpet配置里正常显示，其它均完全失效
已在无其它模组环境测试
![屏幕截图 2023-07-22 193613](https://github.com/Nyan-Work/plusls-carpet-addition/assets/128227112/d988e42f-2b22-4061-a545-2333431911a1)

### To Reproduce

[minecraft-exported-logs-2023-07-22T19-58-46.log](https://github.com/Nyan-Work/plusls-carpet-addition/files/12136372/minecraft-exported-logs-2023-07-22T19-58-46.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
README有写：
> 管理命令: `/pca`

**Comment by sillya1a2** [comment]
sorry for my carelessness:(
