### ISSUE TITLE
[Bug] 无法加载规则

### ISSUE THREAD

**Issue by bAdOoWindy** [Nyan-Work/plusls-carpet-addition#15]
### Minecraft Version

1.20.1

### Plusls Carpet Addition Version

PluslsCarpetAddition-all-0.3.176+56ccc7d-beta

### Carpet Version

fabric-carpet-1.20-1.4.112+v230608

### Fabric API Version

fabric-api-0.86.1+1.20.1

### Description

![52a8c222b930ea90d3cda8948fb6e973](https://github.com/Nyan-Work/plusls-carpet-addition/assets/4119845/11b4f7f7-c99c-4e53-98bf-c86a88c739ae)
![图片](https://github.com/Nyan-Work/plusls-carpet-addition/assets/4119845/cc9d4353-8509-494f-a687-602ce18d1337)
单机, 服务器都试过了, 不加载
/carpet pca没有补全提示

### To Reproduce

直接进入游戏

### Log

[2023-08-03-7.log.gz](https://github.com/Nyan-Work/plusls-carpet-addition/files/12243175/2023-08-03-7.log.gz)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
README有写：
> 管理命令: `/pca`
