### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by Aculoss** [Nyan-Work/plusls-carpet-addition#16]
### Minecraft Version

1.20.1

### Plusls Carpet Addition Version

PluslsCarpetAddition-1.20.1-0.3.176+56ccc7d-beta

### Carpet Version

fabric-carpet-1.20.1-1.4.112+v230626

### Fabric API Version

fabric-api-0.86.1+1.20.1

### Description

Server wont even detect the mod installed.. not on mod load list and carpet rule ignored as no mod to read from.. 

### To Reproduce

Install on server, then run.

### Expected behavior

Mod loading and working.

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Did you try `/pca`?
