### ISSUE TITLE
Mod doesn't load on server

### ISSUE THREAD

**Issue by sternschnaube** [Nyan-Work/plusls-carpet-addition#2]
### Minecraft Version

1.19.3

### Plusls Carpet Addition Version

0.3.144

### Carpet Version

1.4.96+v230201

### Fabric API Version

0.74.0

### Description

Hello, I was using before the build "plusls-carpet-addition-1.19.3-0.2.5-beta+5fa8bc5.jar", which worked fine.

Now after switching to "PluslsCarpetAddition-1.19.3-0.3.144+85a443e-beta.jar", the mod doesn't work anymore.

Carpet says in the log, it can't load the rules, they are not found.

### To Reproduce

/

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Now you need to use /pca to manage the rules.

**Comment by venaminecraft** [comment]
Ohh, oki thanks!
