### ISSUE TITLE
游戏内中文[Feature Request] 

### ISSUE THREAD

**Issue by Adogs1** [Nyan-Work/plusls-carpet-addition#20]
### What new features do you want?

请问能否像/carpet language那样设置zh_cn翻译？？？
可以添加/pca language zh_cn

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 #4 重复。

**Comment by Adogs1** [comment]
> 与 #4 重复。

或许应该说明一下？
