### ISSUE TITLE
PCA同步[Bug] 

### ISSUE THREAD

**Issue by Adogs1** [Nyan-Work/plusls-carpet-addition#21]
### Minecraft Version

1.20.1

### Plusls Carpet Addition Version

0.3.186+ffd08e4 bata

### Carpet Version

1.4.112 +v230608

### Fabric API Version

0.90.0

### Description

pcaSyncPlayerEntity的everyone在true和单人模式下无法使用tweakeroo的预览来查看假人背包内物品，不确定它是否是bug

### To Reproduce

如上

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
PCA 同步协议仅用于服务器不属于 Bug
