### ISSUE TITLE
[Question] "method overwrite conflict" between pca and lithium?

### ISSUE THREAD

**Issue by Silverteal** [Nyan-Work/plusls-carpet-addition#23]
### Question Type

Usages

### Description

`
[main/WARN]: Method overwrite conflict for method_5431 in pca.mixins.json:rule.pcaSyncProtocol.block.MixinAbstractFurnaceBlockEntity from mod pca-1_20_1, previously written by me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.furnace.AbstractFurnaceBlockEntityMixin. Skipping method.
`
`
[main/WARN]: Method overwrite conflict for method_5431 in pca.mixins.json:rule.pcaSyncProtocol.block.MixinBrewingStandBlockEntity from mod pca-1_20_1, previously written by me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.brewing_stand.BrewingStandBlockEntityMixin. Skipping method. 
`
Will this cause any problems?

**Comment by Hendrix-Shen** [comment]
No, there's no problem. All features will work as expected.

**Comment by Silverteal** [comment]
> No, there's no problem. All features will work as expected.

Thanks for answering
