### ISSUE TITLE
[Feature Request] 在README中增加更详细的解释说明

### ISSUE THREAD

**Issue by SilianZ** [Nyan-Work/plusls-carpet-addition#6]
### What new features do you want?

在README中增加更详细的解释说明，包括但不限于“语言设置方法”、“`/pca`”

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Colorflow-exe** [comment]
> ### What new features do you want?
> 在README中增加更详细的解释说明，包括但不限于“语言设置方法”、“`/pca`”
> 
> ### Latest CI build tested
> * [x]  I confirm that the feature I requested is not in the latest CI build.

怎么设置语言啊qwq

**Comment by SilianZ** [comment]
> > ### What new features do you want?
> > 在README中增加更详细的解释说明，包括但不限于“语言设置方法”、“`/pca`”
> > ### Latest CI build tested
> > 
> > * [x]   I confirm that the feature I requested is not in the latest CI build.
> 
> 怎么设置语言啊qwq

`/magiclib language zh_cn`

**Comment by Colorflow-exe** [comment]
> > > ### What new features do you want?
> > > 在README中增加更详细的解释说明，包括但不限于“语言设置方法”、“`/pca`”
> > > ### Latest CI build tested
> > > 
> > > * [x]    I confirm that the feature I requested is not in the latest CI build.
> > 
> > 
> > 怎么设置语言啊qwq
> 
> `/magiclib language zh_cn`

谢谢了qwq
