### ISSUE TITLE
[Bug] 1.19.4中启用墓碑功能，在墓碑被炸毁时仅掉落头颅

### ISSUE THREAD

**Issue by YamaArashiHZ** [Nyan-Work/plusls-carpet-addition#7]
### Minecraft Version

1.19.4

### Plusls Carpet Addition Version

0.3.163+a95078f-beta

### Carpet Version

1.4.101+v230319

### Fabric API Version

0.81.1

### Description

1.19.4中启用墓碑功能，在墓碑被炸毁时仅掉落头颅

### To Reproduce

启用墓碑，死亡后炸毁墓碑（或许仅能由苦力怕炸毁，其他未做测试）

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Cranyozen** [comment]
在 1.20.1 版本测试中  据目前所掌握的测试  所有非玩家挖掘的墓碑在非正常情况下破坏都会导致仅掉落头颅
例如: TNT 爆炸, 苦力怕爆炸, 凋灵之首 等等

**Comment by Hendrix-Shen** [comment]
这个是刻意为之的特性。
