### ISSUE TITLE
[添加特性] 能取消pca指令吗 直接跟以前版本一样

### ISSUE THREAD

**Issue by Colorflow-exe** [Nyan-Work/plusls-carpet-addition#9]
### What new features do you want?

![image](https://github.com/Nyan-Work/plusls-carpet-addition/assets/98727214/2cfb471c-de10-4064-b493-0f05ac44a7ac)

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
这一性质是刻意为之的
